manager/catalog_manager.go
model/rancher_compose.go
model/template.go
model/upgrade_info.go
scripts/all
service/handlers.go
service/routes.go

Fixed the styling issues as reported in the build failures in this PR: https://github.com/rancher/rancher-catalog-service/pull/2

Fixed styling issues reported by go fmt/vet/lint

---

service/handlers.go

Addresses https://github.com/rancher/rancher/issues/2464

Look for x-forwarded-proto when building urls

---

manager/catalog_manager.go

Changes inlcude:
- do git fetch and git reset --hard (instead of just git pull) to ensure catalog fetches and points to git repo head
- Empty the catalogMap before refresh
https://github.com/rancher/rancher/issues/2538
https://github.com/rancher/rancher/issues/2431

Fixes to Catalog refresh when templates are added/removed from git repo

---

manager/catalog_manager.go

Readme.md file can be under a template version also.
It can also be under the top-level template folder.

Changes to support Readme.md under a template version

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/rancher/go-rancher/api/html_writer.go
Godeps/_workspace/src/github.com/rancher/go-rancher/api/url.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_client.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_container.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_external_host_event.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_launch_config.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_machine.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_registry.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_secondary_launch_config.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_storage_pool.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_ubiquity_config.go
manager/catalog.go
manager/catalog_manager.go
model/template.go
service/handlers.go
service/routes.go

Templateversion upgradeinfo

---

manager/catalog.go
service/handlers.go

Added filter category_ne to return templates that do NOT match the given category.
/v1-catalog/templates?category_ne=
UI can pass /v1-catalog/templates?category_ne=system to not list any system templates

Category filter added

---

integration/core/test_catalog_validate.py
manager/catalog.go
manager/catalog_manager.go
scripts/test
scripts/test-warm
scripts/validate

The validate flag starts the Rancher Catalog Service and ensures that the
yaml in the git repository is valid and exits. If it exits 1 there
are errors in the template files.

Add a validate flag to the catalog

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-semver/LICENSE
Godeps/_workspace/src/github.com/rancher/go-rancher/LICENSE
Godeps/_workspace/src/github.com/rancher/go-rancher/api/url.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_add_outputs_input.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_client.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_cluster.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_environment.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_external_service.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_external_volume_event.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_host.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_launch_config.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_load_balancer_config.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_load_balancer_service.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_machine.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_openldapconfig.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_project.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_public_endpoint.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_secondary_launch_config.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_service.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_virtual_machine.go
Godeps/_workspace/src/github.com/rancher/go-rancher/client/generated_virtual_machine_disk.go

https://github.com/rancher/rancher/issues/2943

Godep bump to fix rancher/rancher#2943

---

manager/catalog.go
model/template.go
service/handlers.go

Add catalogId in the template response and Support filter ?catalogId=foo along with ?catalog=foo

Add catalogId in the template respone and Support filter ?catalogId

---

integration/core/test_api.py
manager/catalog.go
model/template.go
service/handlers.go
service/routes.go

Changes to make refresh catalog api /templates?action=refresh. Also removed uuid property from template object.

Changes to make refresh catalog api /templates?action=refresh. Also uuid removed.

---

integration/core/test_api.py
manager/catalog.go
manager/catalog_manager.go

The Service used to get a null pointer error and panic, when rancher-compose file was not found.
Fixed this basic broken functionality.
Fixed https://github.com/rancher/rancher/issues/3102
Cannot think of any integration tests for this PR.

Do not bail out if docker or rancher compose files are missing under templates

---

integration/core/test_api.py
manager/catalog.go
manager/catalog_manager.go
model/error.go
service/handlers.go
service/routes.go

API spec https://github.com/rancher/api-spec/blob/master/specification.md#errors
Adding this as per comments in  https://github.com/rancher/rancher/issues/3002

Error handling to provide error response as per API spec 

---

service/handlers.go

This will allow spaces to be used in catalog names and will fix the issue raised in https://github.com/rancher/rancher/issues/3124

Changes to Url Encode the links in catalog and template resources

---

integration/core/test_api.py
service/handlers.go

The service should return a 204 response on this API, since there is no response object to return.

Return an http 204 - no content response on action=refresh

---

manager/catalog.go

Changes to support reading of files under the nested folders of a template version. Thus any file under say rancher-catalog/ElasticSearch/0/foo/another.yml or rancher-catalog/ElasticSearch/0/foo/bar/some.json will be pulled and added to "files" map in the response.
https://github.com/rancher/rancher/issues/3965
Cannot add individual tests since the testing depends on the catalog structure. Tested manually with a sample catalog repo.

Support files under nested folders of a template version

---

integration/core/test_api.py
manager/catalog.go
model/template.go
service/handlers.go

This flag will indicate if this template should be launched as a system stack within Rancher
https://github.com/rancher/rancher/issues/4648

Added flag isSystem: true/false to the template's config.yml file

---

integration/core/test_catalog_validate.py
manager/catalog_manager.go

Changes to change https to lowercase, else git clone errors out
Added a test for the fix
https://github.com/rancher/rancher/issues/4934

Changes to fix git clone for a url having capital 'https'

---

integration/core/test_api.py
service/handlers.go

Filters out empty upgradeVersionLinks

Filters out empty upgradeVersionLinks

---

integration/core/test_api.py
manager/catalog_manager.go
repo.json

upgradeVersionLinks is updated by comparing versions in place of template's folder numbers.

Compares versions in place of template folder numbers

---

integration/core/test_api.py
manager/catalog.go
model/template.go

Commented the call to create bindings

Disable bindings

---

manager/catalog_manager.go

Changed logic to generate path to rancher-compose.yml

Fixes template path creation

---

manager/catalog_manager.go
repo.json

Changes configFile format

---

integration/core/test_api.py
model/bindings.go

Scale field from binding is removed.

Removes scale from bindings

---

manager/catalog_manager.go

https://github.com/rancher/rancher/issues/5981

Updates CatalogsCollections

---

model/rancher_compose.go

https://github.com/rancher/rancher/issues/6073

Adds upgradeFrom field in rancher-compose

---

integration/core/test_api.py
manager/catalog.go
model/rancher_compose.go
model/template.go
service/handlers.go

`maximumRancherVersion` field is added in rancher-compose `.catalog` section. 
https://github.com/rancher/rancher/issues/6073

Adds maximumRancherVersion

---

manager/catalog_manager.go

https://github.com/rancher/rancher/issues/5960

Disable catalogs

---

integration/core/test_api.py
integration/requirements.txt

Added conditions to check if the template objects and urls array are null.

Corrections in tests

---

manager/catalog.go

https://github.com/rancher/rancher/issues/6306

Change log for missing rancher-compose file

---

service/handlers.go

https://github.com/rancher/rancher/issues/6838

Populate path to readme

---

integration/core/test_api.py

This test uses infra-k8s templates for rancher-catalog https://github.com/rancher/rancher-catalog/tree/master/infra-templates/k8s
The requested template is returned irrespective of the filters, only versionLinks for it are based on the filters. For the requested template with version ID, the upgradeVersionLinks are based on the filters

Test to check versionLinks and upgradeVersionLinks with filters

---

integration/core/test_api.py

Removing the assert so the test won't break on addition of more versions
@cjellick

Remove assert for number of templateVersions
