rancher/rancher-catalog-service

manager/catalog_manager.go, model/rancher_compose.go, model/template.go, model/upgrade_info.go, scripts/all, service/handlers.go, service/routes.go
Fixes to remove existing catalog data, when a new catalogUrl is provided. Also fixed the 'self-link' of template metadata - the link should use the path property of a template and not the name.
https://github.com/rancher/rancher/issues/2354
=> Changing catalog URL doesn't work with existing DATA folder

manager/catalog_manager.go, service/handlers.go
Changes: Return the template object within the block and also a boolean return value to indicate if the upgrade info is found.
=> Fixed the upgardeinfo that was broken with validation fixes. 

main.go, manager/catalog_manager.go, model/rancher_compose.go, service/routes.go
Changes include: 
- Remove config.yml file from template version folders. 
- Also Service will now listen at start and retrun 503 until the catalog is ready. 
- Also log the git clone output.
- Correct the yaml fields to be underscore lowercase separated
=> Changes to remove config.yml file from template version folders and more

README.md, manager/catalog_manager.go
Let's not confuse people into believing that you have to use a github repo for the catalog.
=> Fix wording for the general case as the catalogUrl may be any valid git url.

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/go-semver/semver/semver.go, Godeps/_workspace/src/github.com/coreos/go-semver/semver/semver_test.go, Godeps/_workspace/src/github.com/coreos/go-semver/semver/sort.go, manager/catalog_manager.go, model/rancher_compose.go, model/template.go, service/handlers.go
Added support for property 'minimumRancherVersion' on the templates .catalog section
Added a filter on the api:  /v1-catalog/templates?minimumRancherVersion_lte=<version>
Fixes https://github.com/rancher/rancher/issues/2489
=> Support for minimumRancherVersion property on templates and added a filter minimumRancherVersion_lte

manager/catalog_manager.go, model/rancher_compose.go, model/template.go, service/handlers.go, service/routes.go
Changes to support:
1) Additional fields to config.yml [maintainer, license, projectURL] 
2) readme.md file under each template, a link will be provided in the response
3) output section in .catalog section of templates
https://github.com/rancher/rancher/issues/2643
=> Additional config fields added 

manager/catalog.go, manager/catalog_manager.go, service/handlers.go, service/routes.go
- Accepts a comma separated list of git repo urls in the format id1:url1,id2:url2,...
API /v1-catalog/templates will list templates from all catalogs
API /v1-catalog/templates?catalog={catalog_id} will list templates from specified catalog
- Also added new API to list Catalogs /v1-catalog/catalogs. 
- Changed code use git pull instead of git reset to refresh the Catalogs
- Added id to the template version as catalog:template_name:version
=> Support for multiple catalog repos.

manager/catalog.go, manager/catalog_manager.go, service/handlers.go, service/routes.go
So the id will be of format catalogId:templateId:versionId
Changed the routes accordingly to /v1-catalog/templates/{id}
=> Changes to use ':' as the separator in the template id. 

manager/catalog.go, manager/catalog_manager.go, service/handlers.go, service/routes.go
Routes changed to 
/v1-catalog/templates/{id}?image
/v1-catalog/templates/{id}?readme
=> Change the way images and readme file is accessed

manager/catalog_manager.go
Now catalog service supports both `-catalogUrl key=value -catalogUrl key2=value2` and `-catalogUrl key=value,key2=value2`
=> Changes to let catalogUrl accept comma separated list of git repos 

manager/catalog.go
Changing the level to debug since this line gets printed on every background catalog refresh (default every 5 minutes)
=> Changing log level to debug, this line prints every 5 mins

integration/core/test_api.py, manager/catalog.go, manager/catalog_manager.go
There is repeated attempts made to clone all catalogs when there is a failure encountered in cloning one of the catalogs. 
This happens because catalog service halts upon failure and rancher server keeps on restarting the service.
Fixed the service to not halt upon failure to clone for one catalog when multiple catalogs are provided.
https://github.com/rancher/rancher/issues/3003
https://github.com/rancher/rancher/issues/3004
https://github.com/rancher/rancher/issues/3002
=> Changes to continue running catalog service even if one catalog fails to clone

integration/core/test_api.py, manager/catalog.go, model/template.go, service/handlers.go, service/routes.go
The folder should be at same level as templates/ folder.
Any such folder at same level as templates/ can be supported, provided
it has name of format {xyz}-templates/
By default, all the templates under templates/ and say {xyz}-templates/ folders
will be loaded by http://localhost:8088/v1-catalog/templates/
To list only the contents of say the kubernetes-templates folder, pass filter
http://localhost:8088/v1-catalog/templates?templateBase_eq=kubernetes
[http://localhost:8088/v1-catalog/templates?templateBase_eq=xyz]
To not list the contents of such a folder, pass filter
http://localhost:8088/v1-catalog/templates?templateBase_ne=kubernetes
[http://localhost:8088/v1-catalog/templates?templateBase_ne=xyz]
Also, the fields 'rancher-compose' and 'docker-compose' will not be present anymore on …
=> Changes to support kubernetes-templates/ folder in the repo

service/handlers.go
Url encoding was being applied to the template ID itself and that caused the templateId to be added with the first letter lowercase to the versrionLinks (since URLEncoder thinks its the scheme in a valid url)
Fixed this by encoding after forming the url for the versions.
Tested manually, cannot add a specifc test for this fix.
Issue: https://github.com/rancher/rancher/issues/3955
Issue: https://github.com/rancher/rancher/issues/3971
=> The URLEncoding should be applied after forming the complete URL 

manager/catalog.go, manager/catalog_manager.go
The service now first checks if the catalog by its name and repoURL
already exists under ./DATA/ folder. If it does then it just pulls
updates and serves the catalog without cloning newly. In case the pull
fails then whatever is on the disk is served.
If the catalogName or repoURL do not match to existing catalog, then
that catalog is newly cloned.
Tested manually, cannot test using integration tests.
https://github.com/rancher/rancher/issues/3964
=> Changes to support pre-cloned catalog present on disk.

integration/core/test_api.py, manager/catalog.go, scripts/test
Fix the code that derives the path to be put in the "files" map.
It was broken for a template version having multiple digits due to indexOf calculations
Now the fix is to split the path around the version and use the latter part.
https://github.com/rancher/rancher/issues/4195
=> Fix the code that derives the path of a file under a template version

integration/core/test_api.py, service/handlers.go
This filter is supported for /templates API. 
We need to support it also for /templates/{catalogid:templateid}
The reponse should list only those versions of this template which satisfy the minimumRancherVersion_lte filter
Added a test for this filter.
=> Support minimumRancherVersion_lte filter for /templates/{catalogid:templateid} path

integration/core/test_api.py, service/handlers.go
Applying minimumRancherVersion_lte filter also to upgradeVersionLinks returned for a template version.
Also the template version will be returned provided its
minimumRancherVersion is less than or equal to the passed rancherVersion
Added tests based on qa-catalog
https://github.com/rancher/rancher/issues/5192
=> Applying minimumRancherVersion_lte filter also to upgradeVersionLinks

integration/core/test_api.py, main.go, manager/catalog.go, manager/catalog_manager.go, repo.json, scripts/test, service/handlers.go
Rancher-catalog-service can accept catalog URLs from a JSON file along with the command line argument. A sample JSON file is provided: repo.json. User can include any branch of the repository in the json. The service still accepts all command line args as it did previously
=> Branch support

manager/catalog.go
In our workflow we have one repository per catalog template so that we can use git properly without duplicating the code and thus having comprehensive diffs, resolvable conflicts and so on...
When use tags to release a template and have a script that creates the whole catalog for all ours templates using git subtree.
We'd like to be able to use git submodules instead, and so this patch may allow us to do it.
=> Allow to use submodules in catalog

integration/core/test_api.py, manager/catalog_manager.go, repo.json
The configFile is now in the format of a JSON object with "catalogs" as a key, that has a JSON array of catalogs. Sample file provided is repo.json:
{
"catalogs":[
{
"name":"qa-catalog",
"repoURL":"https://github.com/rancher/qa-catalog",
"branch":"master"
},
{
"name":"rancher-catalog",
"repoURL":"https://github.com/rancher/rancher-catalog",
"branch":"master"
}
]
}
=> Changed format of configFile to an object containing catalogs field

manager/catalog.go, model/rancher_compose.go, model/template.go
'labels' key is added to the templateVersion, which displays 'labels' provided in rancher-compose.yml
=> Adds 'labels' key for templateVersion

manager/catalog_manager.go
https://github.com/rancher/rancher/issues/5960
The `log.Fatal` message when all catalogs are disabled caused the catalog-service to stop. It has been changed to log.Info, so catalog-service doesn't stop, and works as earlier once catalog urls are provided again.
=> Remove log.fatal message

manager/catalog.go, manager/catalog_manager.go, service/routes.go
https://github.com/rancher/rancher/issues/4903
https://github.com/rancher/rancher/issues/5352
The catalog-service waits till all catalogs are read from cache before it starts accepting requests. That results in a 503 "Service not available" error when the catalog-service is still being initialized (read from cache). This PR removes the wait on catalog-service being ready. It also reverses the order of loading catalogs into metadata by first reading from cache and then doing `git pull`. This is because when github is disabled, `git pull` takes time to fail and earlier no catalogs were displayed, where as we can now display the catalogs from cache as soon as the request to catalog-service is made.
=> Read cache before git pull

manager/catalog_manager.go
https://github.com/rancher/rancher/issues/6072
This PR removes the catalogs deleted in the UI from the disk. In order to keep the embedded infra, library and community catalogs, they need to have a `.nopurge` file in them.
=> Remove deleted catalogs from disk

manager/catalog.go
https://github.com/rancher/rancher/issues/6306
The message `Skipping template` will be shown in logs if rancher-compose doesn't exist.
=> Change 'skipping template' to Info log

manager/catalog_manager.go
`GetNewTemplateVersions` is one of the functions called for route `/v1-catalog/templates/{catalog_template_version_Id}`. This function has a call to refreshCatalog that was not needed here since the `startCatalogBackgroundPoll` function will refresh on fixed interval, and also changing the catalog entries will cause a refresh. This PR removes the call to `refreshCatalog` from `GetNewTemplateVersions`
=> Remove refreshCatalog call from GetNewTemplateVersions

service/handlers.go
Removes the filtering of templateversion by ID based on min/max filters. Min/max filters applied only on upgradeVersionLinks (getting templateversion by ID) and versionLinks(template)
https://github.com/rancher/rancher/issues/6704
=> Min/max filters only on upgradeVersionLinks and versionLinks

integration/core/test_api.py, main.go, manager/catalog.go, manager/catalog_manager.go
https://github.com/rancher/rancher/issues/7230
`startCatalogBackgroundPoll` was being called twice, once when catalog-service is launched and once when catalog reload was done from UI. This PR calls it only once from main.go
Because it was called twice, the default case was invoked in refreshCatalog and the "Refresh for catalog is already in progress, skipping" message was getting repeated.
=> Catalog background poll
